-- Outdated: Drop the not null constraint (you can use ALTER TABLE depending on your database)
-- ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID DROP NOT NULL;

-- Insert users into USERX table
INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Admin', 'Istrator', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'admin', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Susi', 'Kaufgern', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user1', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Max', 'Mustermann', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user2', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Elvis', 'The King', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'elvis', NULL, '2024-01-01 00:00:00');
--Add me :)
INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE,EMAIL)
VALUES (FALSE, TRUE, 'Adriano', 'Paganini', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'adriano', NULL, '2024-01-01 00:00:00','PaganiniAdriano1@gmail.com');

-- Insert roles into USERX_USERX_ROLE table by looking up the corresponding user ID
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'CUSTOMER');


INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'CUSTOMER');

-- Update CREATE_USER_ID fields after the initial insert
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'admin';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user1';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user2';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis') WHERE USERNAME = 'elvis';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano') WHERE USERNAME = 'elvis';


-- Outdated: Add the not null constraint back
-- ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID SET NOT NULL;

--Add Products

INSERT INTO PRODUCT (CREATE_USER_ID, NAME, DESCRIPTION, PRICE, STOCK, DISCOUNT, DELETED, AVG_SCORE, CREATE_DATE)
SELECT ID, 'DDR5 32GB', 'Standard RAM Kit', 1015.99, 13, 0.10, FALSE, 3.7, TIMESTAMP '2000-01-01 00:00:00'
FROM USERX WHERE USERNAME = 'elvis';
-- ADD Image link
INSERT INTO PRODUCT_IMAGES
VALUES((SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'), 'https://imgs.search.brave.com/i_ObPlbE274H-SU6P7WojePHmrw0YRayTHKsHxuy4N8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9nemhs/cy5hdC9vY3RyaS9t/ZWRpdW1fTGFyaV9C/YXRfc2h1dHRlcnN0/b2NrX2E1ZDk2MTY4/YWEuanBn');

INSERT INTO PRODUCT (CREATE_USER_ID, NAME, DESCRIPTION, PRICE, STOCK, DISCOUNT, DELETED, AVG_SCORE, CREATE_DATE)
SELECT ID, 'Aerondight Silver Sword', 'Lady of the Lake approved. Better for monsters than for humans.', 1273.00, 1, 0.0, FALSE, 5.0, CURRENT_TIMESTAMP
FROM USERX WHERE USERNAME = 'elvis';
-- ADD Image link
INSERT INTO PRODUCT_IMAGES
VALUES((SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'), 'https://imgs.search.brave.com/-hRbsdcQiyinkXE7P9aDa2ODhSEsV3J8sBUN83nqHPE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTF1VVB3T1BXTUwu/anBn');

INSERT INTO PRODUCT (CREATE_USER_ID, NAME, DESCRIPTION, PRICE, STOCK, DISCOUNT, DELETED, AVG_SCORE, CREATE_DATE)
SELECT ID, 'Guardian Angel', 'Upon taking lethal damage, restores 50% of base health. Perfect for a Last Stand.', 3000.00, 2, 0.0, FALSE, 4.8, CURRENT_TIMESTAMP
FROM USERX WHERE USERNAME = 'elvis';
-- ADD Image link
INSERT INTO PRODUCT_IMAGES
VALUES((SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'), 'https://wiki.leagueoflegends.com/en-us/images/Guardian_Angel_item.png?da4ce');

INSERT INTO PRODUCT (CREATE_USER_ID, NAME, DESCRIPTION, PRICE, STOCK, DISCOUNT, DELETED, AVG_SCORE, CREATE_DATE)
SELECT ID, 'Schrödinger’s Laptop', 'Simultaneously the best and worst laptop until you open it.', 500.00, 2, 0.00, FALSE, 2.5, CURRENT_TIMESTAMP
FROM USERX WHERE USERNAME = 'elvis';
-- ADD Image link
INSERT INTO PRODUCT_IMAGES
VALUES((SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'), 'https://imgs.search.brave.com/Ukn9qJDe_Q0ZXy7ZrrA-gQ538aREJNyLP_EFgzca1hU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bW9zLmNtcy5mdXR1/cmVjZG4ubmV0L3BR/aHNiNmJqa29yckNa/RjNwWUd0eEouanBn');

INSERT INTO PRODUCT (CREATE_USER_ID, NAME, DESCRIPTION, PRICE, STOCK, DISCOUNT, DELETED, AVG_SCORE, CREATE_DATE)
SELECT ID, 'Pip-Boy 3000', 'Essential for vault life. Radiation sensor not included.', 3000.00, 13, 0.11, FALSE, 4.5, CURRENT_TIMESTAMP
FROM USERX WHERE USERNAME = 'elvis';
-- ADD Image link
INSERT INTO PRODUCT_IMAGES
VALUES((SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'), 'https://store.ign.com/cdn/shop/files/Fallout-Pip-Boy-3000-Replica.jpg?v=1763232682&width=990');

INSERT INTO PRODUCT (CREATE_USER_ID, NAME, DESCRIPTION, PRICE, STOCK, DISCOUNT, DELETED, AVG_SCORE, CREATE_DATE)
SELECT ID, 'Non-Stop Energy Drink', 'A favorite among Stalkers in the Zone. Restores stamina, but watch out for anomalies.', 15.50, 50, 0.00, FALSE, 4.7, CURRENT_TIMESTAMP
FROM USERX WHERE USERNAME = 'elvis';
-- ADD Image link
INSERT INTO PRODUCT_IMAGES
VALUES((SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'), 'https://chornobyl.shop/Media/shop-20120/drinks/non-stop-stalker-4.jpg');

--ELVIS

-- Add Subscription to DDR5 32GB
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='DDR5 32GB'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));
-- Add Subscription to Aerondight Silver Sword
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Aerondight Silver Sword'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));
-- Add Subscription to Guardian Angel
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Guardian Angel'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));
-- Add Subscription to Schrödinger’s Laptop
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Schrödinger’s Laptop'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));
-- Add Subscription to Pip-Boy 3000
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Pip-Boy 3000'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));
-- Add subscription to Non-Stop Energy Drink
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Non-Stop Energy Drink'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));

-- Add Types TO DDR5 Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      , 'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      ,'DISCOUNTUPDATE');

--Add Channels TO DDR5 Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      , 'EMAIL');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      , 'SMS');


-- Add Types TO Aerondight Silver Sword Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      , 'NAMEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      ,'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      ,'DISCOUNTUPDATE');

-- Add Channels TO Aerondight Silver Sword Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      , 'EMAIL');


-- Add Types TO Guardian Angel Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      , 'DESCRIPTIONUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      ,'RESTOCK');

-- Add Channels TO Guardian Angel Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      , 'SMS');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      , 'EMAIL');


-- Add Types TO Schrödinger’s Laptop Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      , 'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      ,'DISCOUNTUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      ,'DESCRIPTIONUPDATE');

-- Add Channels TO Schrödinger’s Laptop Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      , 'EMAIL');


-- Add Types TO Pip-Boy 3000 Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      , 'NAMEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      ,'RESTOCK');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      ,'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      ,'DESCRIPTIONUPDATE');

-- Add Channels TO Pip-Boy 3000 Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      , 'SMS');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      , 'EMAIL');


-- Add Types TO Non-Stop Energy Drink Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'))
      , 'DISCOUNTUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'))
      ,'PRICEUPDATE');

-- Add Channels TO Non-Stop Energy Drink Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'))
      , 'SMS');


-- 1. Notification (SMS/Channel 1, Status 1)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 1, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The discount of "DDR5 32GB" has been updated from 0.05 to 0.03.'
FROM USERX WHERE USERNAME = 'elvis';

-- 2. Notification (SMS/Channel 1, Status 1)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 1, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The price of "DDR5 32GB" has been updated from 879.99 to 900.00.'
FROM USERX WHERE USERNAME = 'elvis';

-- 3. Notification (Email/Channel 0, Status 2)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 2, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The discount of "DDR5 32GB" has been updated from 0.05 to 0.03.'
FROM USERX WHERE USERNAME = 'elvis';

-- 4. Notification (Email/Channel 0, Status 2)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 2, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The price of "DDR5 32GB" has been updated from 879.99 to 900.00.'
FROM USERX WHERE USERNAME = 'elvis';

-- 5. NEU: Notification mit Status 0 (z.B. QUEUED)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 0, CURRENT_TIMESTAMP,
       '12.01.2026 10:30 - New update pending for "DDR5 32GB".'
FROM USERX WHERE USERNAME = 'elvis';


--Add Address to each User
--elvis
INSERT INTO ADDRESS(USER_ID,NUMBER,POSTAL_CODE,CITY,COUNTRY,STREET,EXTRA)
SELECT ID, '40','6020','Innsbruck', 'Austria','Technikerstraße', 'RR21'
FROM USERX
WHERE USERNAME = 'elvis' OR USERNAME = 'admin' OR USERNAME = 'user1' OR USERNAME = 'user2';

--Add myself (adriano)

-- Add Subscription to DDR5 32GB
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='DDR5 32GB'), (SELECT ID FROM USERX WHERE USERNAME = 'adriano'));

-- Add Subscription to Aerondight Silver Sword
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Aerondight Silver Sword'), (SELECT ID FROM USERX WHERE USERNAME = 'adriano'));

-- Add Subscription to Guardian Angel
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Guardian Angel'), (SELECT ID FROM USERX WHERE USERNAME = 'adriano'));

-- Add Subscription to Schrödinger’s Laptop
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Schrödinger’s Laptop'), (SELECT ID FROM USERX WHERE USERNAME = 'adriano'));

-- Add Subscription to Pip-Boy 3000
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Pip-Boy 3000'), (SELECT ID FROM USERX WHERE USERNAME = 'adriano'));

-- Add subscription to Non-Stop Energy Drink
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Non-Stop Energy Drink'), (SELECT ID FROM USERX WHERE USERNAME = 'adriano'));

-- Add Types TO DDR5 Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      , 'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      ,'DISCOUNTUPDATE');

--Add Channels TO DDR5 Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      , 'EMAIL');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'))
      , 'SMS');

-- Add Types TO Aerondight Silver Sword Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      , 'NAMEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      ,'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      ,'DISCOUNTUPDATE');

-- Add Channels TO Aerondight Silver Sword Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'))
      , 'EMAIL');

-- Add Types TO Guardian Angel Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      , 'DESCRIPTIONUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      ,'RESTOCK');

-- Add Channels TO Guardian Angel Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      , 'SMS');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'))
      , 'EMAIL');

-- Add Types TO Schrödinger’s Laptop Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      , 'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      ,'DISCOUNTUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      ,'DESCRIPTIONUPDATE');

-- Add Channels TO Schrödinger’s Laptop Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'))
      , 'EMAIL');

-- Add Types TO Pip-Boy 3000 Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      , 'NAMEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      ,'RESTOCK');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      ,'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      ,'DESCRIPTIONUPDATE');

-- Add Channels TO Pip-Boy 3000 Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      , 'SMS');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'))
      , 'EMAIL');

-- Add Types TO Non-Stop Energy Drink Subscription
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'))
      , 'DISCOUNTUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'))
      ,'PRICEUPDATE');

-- Add Channels TO Non-Stop Energy Drink Subscription
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'adriano')
                                      AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'))
      , 'SMS');

-- 1. Notification (SMS/Channel 1, Status 1)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 1, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The discount of "DDR5 32GB" has been updated from 0.05 to 0.03.'
FROM USERX WHERE USERNAME = 'adriano';

-- 2. Notification (SMS/Channel 1, Status 1)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 1, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The price of "DDR5 32GB" has been updated from 879.99 to 900.00.'
FROM USERX WHERE USERNAME = 'adriano';

-- 3. Notification (Email/Channel 0, Status 2)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 2, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The discount of "DDR5 32GB" has been updated from 0.05 to 0.03.'
FROM USERX WHERE USERNAME = 'adriano';

-- 4. Notification (Email/Channel 0, Status 2)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 2, CURRENT_TIMESTAMP,
       '12.01.2026 10:23 - The price of "DDR5 32GB" has been updated from 879.99 to 900.00.'
FROM USERX WHERE USERNAME = 'adriano';

-- 5. NEU: Notification mit Status 0 (z.B. QUEUED)
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 0, CURRENT_TIMESTAMP,
       '12.01.2026 10:30 - New update pending for "DDR5 32GB".'
FROM USERX WHERE USERNAME = 'adriano';

--Add Address to each User
INSERT INTO ADDRESS(USER_ID,NUMBER,POSTAL_CODE,CITY,COUNTRY,STREET,EXTRA)
SELECT ID, '40','6020','Innsbruck', 'Austria','Technikerstraße', 'RR21'
FROM USERX
WHERE USERNAME = 'adriano' OR USERNAME = 'admin' OR USERNAME = 'user1' OR USERNAME = 'user2';



-- add comments
-- Reviews for DDR5 32GB
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (5.0, (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'A small price to pay for RAM.');
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (3.0, (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'This is the most expensive part of my whole build...');

-- Reviews for Aerondight Silver Sword
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (5.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'Even works on highwaymen.');
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (4.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'Very sharp, cut my thumb.');

-- Reviews for Guardian Angel
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (3.5, (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'Did not even need it, Zilean had my back...');
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (4.5, (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'Works wonders, too bad it does not increase my skills.');

-- Reviews for Schrödinger’s Laptop
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (5.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'Outperforms my 15K build for 500.');
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (1.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'Thespacebarisbroken:(');

-- Reviews for Pip-Boy 3000
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (5.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'Offers nice radio for those morning runs!');
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (2.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'Interface is ancient, almost got me killed. Still nice to have though.');

-- Reviews for Non-Stop Energy Drink
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (4.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'adriano'), 'Tasty, not sure how much it really helps.');
INSERT INTO REVIEW (SCORE, PRODUCT_ID, TIMESTAMP, USER_ID, CONTENT)
VALUES (5.0, (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink'), CURRENT_TIMESTAMP, (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'At least we still got some nice drinks.');

-- add orders for adriano
-- Insert the Order
INSERT INTO orders (TOTAL, TIMESTAMP, USER_ID, ORDER_NUMBER, BILLING_CITY, BILLING_COUNTRY, BILLING_POSTAL_CODE, BILLING_STREET, STATUS)
VALUES (
           1015.89,
           CURRENT_TIMESTAMP,
           (SELECT ID FROM USERX WHERE USERNAME = 'adriano'),
           'ORD-ADRIANO-CONFIRMED',
           'Innsbruck', 'Austria', '6020', 'Technikerstraße',
           'CONFIRMED'
       );

-- Insert the Item (1x DDR5 32GB)
INSERT INTO order_item (ORDER_ID, PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE_AT_PURCHASE)
VALUES (
           (SELECT ID FROM orders WHERE ORDER_NUMBER = 'ORD-ADRIANO-CONFIRMED'),
           (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'),
           'DDR5 32GB',
           1,
           1015.99
       );

-- Insert the Order
INSERT INTO orders (TOTAL, TIMESTAMP, USER_ID, ORDER_NUMBER, BILLING_CITY, BILLING_COUNTRY, BILLING_POSTAL_CODE, BILLING_STREET, STATUS)
VALUES (
           5031.97, -- (2 * 1015.99) + 3000.00 (approximate total)
           CURRENT_TIMESTAMP,
           (SELECT ID FROM USERX WHERE USERNAME = 'adriano'),
           'ORD-ADRIANO-PENDING',
           'Innsbruck', 'Austria', '6020', 'Technikerstraße',
           'PENDING'
       );

-- Insert the first item (2x DDR5 32GB)
INSERT INTO order_item (ORDER_ID, PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE_AT_PURCHASE)
VALUES (
           (SELECT ID FROM orders WHERE ORDER_NUMBER = 'ORD-ADRIANO-PENDING'),
           (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB'),
           'DDR5 32GB',
           2,
           1015.99
       );

-- Insert the second item (1x Guardian Angel)
INSERT INTO order_item (ORDER_ID, PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE_AT_PURCHASE)
VALUES (
           (SELECT ID FROM orders WHERE ORDER_NUMBER = 'ORD-ADRIANO-PENDING'),
           (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel'),
           'Guardian Angel',
           1,
           3000.00
       );

-- AI generated Addition for Other users!
-- =========================
-- SUBSCRIPTIONS (missing users)
-- =========================

-- ADMIN
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='DDR5 32GB'), (SELECT ID FROM USERX WHERE USERNAME='admin'));
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Guardian Angel'), (SELECT ID FROM USERX WHERE USERNAME='admin'));

-- Types -> ADMIN / DDR5 32GB
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB')),
       'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB')),
       'DISCOUNTUPDATE');

-- Channels -> ADMIN / DDR5 32GB
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'DDR5 32GB')),
       'EMAIL');

-- Types -> ADMIN / Guardian Angel
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel')),
       'RESTOCK');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel')),
       'DESCRIPTIONUPDATE');

-- Channels -> ADMIN / Guardian Angel
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel')),
       'SMS');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Guardian Angel')),
       'EMAIL');


-- USER1
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Pip-Boy 3000'), (SELECT ID FROM USERX WHERE USERNAME='user1'));
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Non-Stop Energy Drink'), (SELECT ID FROM USERX WHERE USERNAME='user1'));

-- Types -> USER1 / Pip-Boy 3000
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000')),
       'RESTOCK');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000')),
       'PRICEUPDATE');

-- Channels -> USER1 / Pip-Boy 3000
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000')),
       'EMAIL');
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Pip-Boy 3000')),
       'SMS');

-- Types -> USER1 / Non-Stop Energy Drink
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink')),
       'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink')),
       'DISCOUNTUPDATE');

-- Channels -> USER1 / Non-Stop Energy Drink
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user1')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Non-Stop Energy Drink')),
       'SMS');


-- USER2
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Aerondight Silver Sword'), (SELECT ID FROM USERX WHERE USERNAME='user2'));
INSERT INTO SUBSCRIPTION(PRODUCT_ID, USER_ID)
VALUES((SELECT ID FROM PRODUCT WHERE NAME='Schrödinger’s Laptop'), (SELECT ID FROM USERX WHERE USERNAME='user2'));

-- Types -> USER2 / Aerondight Silver Sword
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword')),
       'NAMEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword')),
       'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword')),
       'DISCOUNTUPDATE');

-- Channels -> USER2 / Aerondight Silver Sword
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Aerondight Silver Sword')),
       'EMAIL');

-- Types -> USER2 / Schrödinger’s Laptop
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop')),
       'DESCRIPTIONUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop')),
       'PRICEUPDATE');

-- Channels -> USER2 / Schrödinger’s Laptop
INSERT INTO NOTIFICATION_TYPES(SUBSCRIPTION_ID, CHANNELS)
VALUES((SELECT ID FROM SUBSCRIPTION
        WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'user2')
          AND PRODUCT_ID = (SELECT ID FROM PRODUCT WHERE NAME = 'Schrödinger’s Laptop')),
       'EMAIL');


-- =========================
-- NOTIFICATIONS (ensure each user has status 0,1,2)
-- =========================

-- ADMIN: one notification for each status 0,1,2
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 0, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - New update pending for "DDR5 32GB".'
FROM USERX WHERE USERNAME = 'admin';

INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 1, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - The price of "DDR5 32GB" has been updated from 1015.99 to 999.99.'
FROM USERX WHERE USERNAME = 'admin';

INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 2, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - Delivery failed for "DDR5 32GB" update notification.'
FROM USERX WHERE USERNAME = 'admin';


-- USER1: one notification for each status 0,1,2
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 0, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - New update pending for "Pip-Boy 3000".'
FROM USERX WHERE USERNAME = 'user1';

INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 1, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - "Pip-Boy 3000" is back in stock.'
FROM USERX WHERE USERNAME = 'user1';

INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 2, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - Delivery failed for "Pip-Boy 3000" restock notification.'
FROM USERX WHERE USERNAME = 'user1';


-- USER2: one notification for each status 0,1,2
INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 0, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - New update pending for "Aerondight Silver Sword".'
FROM USERX WHERE USERNAME = 'user2';

INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 0, 1, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - The discount of "Aerondight Silver Sword" has been updated from 0.00 to 0.05.'
FROM USERX WHERE USERNAME = 'user2';

INSERT INTO NOTIFICATION (USER_ID, CHANNEL, STATUS, TIMESTAMP, MESSAGE)
SELECT ID, 1, 2, CURRENT_TIMESTAMP,
       '13.01.2026 10:26 - Delivery failed for "Aerondight Silver Sword" discount notification.'
FROM USERX WHERE USERNAME = 'user2';