-- Outdated: Drop the not null constraint (you can use ALTER TABLE depending on your database)
-- ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID DROP NOT NULL;

-- Insert users into USERX table
INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Admin', 'Istrator', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'admin', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Susi', 'Kaufgern', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user1', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Max', 'Mustermann', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user2', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (DELETED, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (FALSE, TRUE, 'Elvis', 'The King', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'elvis', NULL, '2024-01-01 00:00:00');

-- Insert roles into USERX_USERX_ROLE table by looking up the corresponding user ID
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'CUSTOMER');

-- Update CREATE_USER_ID fields after the initial insert
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'admin';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user1';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user2';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis') WHERE USERNAME = 'elvis';

-- Outdated: Add the not null constraint back
-- ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID SET NOT NULL;


--Add Product

INSERT INTO PRODUCT (ID, CREATE_USER_ID,NAME, DESCRIPTION,PRICE,STOCK,DISCOUNT,DELETED,AVG_SCORE, CREATE_DATE)
VALUES(1000,(SELECT ID FROM USERX WHERE USERNAME = 'elvis'),'DDR5 32GB','Standard RAM Kit',879.99,13,0.05,FALSE,3.7, TIMESTAMP '2000-01-01 00:00:00');


-- Add Subscription to this Product
INSERT INTO SUBSCRIPTION(ID, PRODUCT_ID, USER_ID)
VALUES(1000,(SELECT ID FROM PRODUCT WHERE NAME='DDR5 32GB'), (SELECT ID FROM USERX WHERE USERNAME = 'elvis'));

-- Ad Types
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES(SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'PRICEUPDATE');
INSERT INTO SUBSCRIPTION_TYPES(SUBSCRIPTION_ID, TYPES)
VALUES(SELECT ID FROM SUBSCRIPTION WHERE USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'PRICEUPDATE');

